# Generated by Django 4.2.7 on 2025-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='notification_type',
            field=models.CharField(choices=[('account', 'Личный кабинет'), ('email', 'Email'), ('telegram', 'Telegram'), ('all', 'Все способы')], default='account', max_length=20),
        ),
    ]
