# Generated by Django 4.2.7 on 2025-12-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_test_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Один вариант ответа'), ('multiple_choice', 'Множественный выбор'), ('text_input', 'Ввод текста'), ('number_input', 'Ввод числа')], default='single_choice', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='notification_type',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Типы уведомлений'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Организатор'), ('student', 'Студент')], default='teacher', max_length=20),
        ),
    ]
