# Generated by Django 4.2.7 on 2025-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Один вариант ответа'), ('multiple_choice', 'Множественный выбор'), ('text_input', 'Ввод текста'), ('number_input', 'Ввод числа'), ('matching', 'Соотнесение'), ('matrix', 'Матричный вопрос')], default='single_choice', max_length=20, verbose_name='Тип вопроса'),
        ),
    ]
